### ISSUE TITLE
Add clean up old lambda's example

### ISSUE THREAD

**Issue by DavidWells** [DavidWells/serverless-workshop#12]
This will clean up older versions of functions. See https://www.npmjs.com/package/serverless-prune-plugin for more details

```yml
service: using-prune-plugin-example

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: ${self:custom.lambda.pruneStage}
    number: 5
  lambda:
    pruneStage: ${self:custom.lambda.versioning.${self:provider.stage}, 'false'}
    versioning:
      dev: false
      staging: true
      prod: true

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  runtime: nodejs8.10
  versionFunctions: ${self:custom.lambda.pruneStage}
```
