### ISSUE TITLE
Add remove stage postfix from stackName example

### ISSUE THREAD

**Issue by DavidWells** [DavidWells/serverless-workshop#13]
Remove the automatic postfix from production stack name.

By default stacks are output to:

`my-stack-name-dev`, `my-stack-name-prod`, `my-stack-name-{stagexyz}`

This variable setup will remove the postfix from the `prod` stack

```yml
service: whatever-will-be-overriden

custom:
  postfix:
    prod: ''

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'prod'}
  stackName: my-stack-name${self:custom.postfix.${self:provider.stage}, '-${self:provider.stage}'}

```

This will remove `-prod` from the production stack and it will be named `my-stack-name`

The `dev` stack will be named `my-stack-name-dev`
