### ISSUE TITLE
Nested stacks example

### ISSUE THREAD

**Issue by DavidWells** [DavidWells/serverless-workshop#17]
From [here](https://github.com/tgajdoski/serverless-multitenant/blob/2ee23b59a3bc56622c507562524a157df1dab666/user-service/serverless.yml#L63-L87)

```yml
plugins:
  - aws-nested-stacks-plugin

resources:
  Resources:
    cognitoFormStack:
      Type: AWS::CloudFormation::Stack
      Properties:
       # ref https://github.com/tgajdoski/serverless-multitenant/tree/2ee23b59a3bc56622c507562524a157df1dab666/user-service/nested-stacks
        TemplateURL: 'https://s3-${self:custom.myRegion}.amazonaws.com/###path###/user-pool-client.cform'
        TimeoutInMinutes: '60'
        Parameters:
          StackPrefix: ${self:custom.myStage}
          PostConfirmationLambdaName:
            "Fn::Join":
              - '-'
              - - ${self:custom.myStage}
                - ${self:service} 
                - 'userConfirmed'
          CustomMessageLambdaName: 
            "Fn::Join":
              - '-'
              - - ${self:custom.myStage}
                - ${self:service}                
                - 'customMessages'
          PreSignUpLambdaName: 
            "Fn::Join":
              - '-'
              - - ${self:custom.myStage}
                - ${self:service}
                - 'preSignUp'
```
