### ISSUE TITLE
Advanced YAML - using anchors

### ISSUE THREAD

**Issue by DavidWells** [DavidWells/serverless-workshop#18]
Ref https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

Examle:

```yml
custom:
  BaseFunctionConfig: &BaseFunctionConfig
    FunctionName: &FunctionName
      handler: file.handler
  ExtendedFunctionConfig: &ExtendedFunctionConfig
    FunctionName:
      <<: *FunctionName
      provisionedConcurrency: 1
  functions:
    staging:
      <<: *BaseFunctionConfig
    production:
      <<: *ExtendedFunctionConfig

functions: ${self:custom.functions.${self:provider.stage}}
```
